//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma2020.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diploma2020.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № счёта.
        /// </summary>
        internal static string AccountLbl {
            get {
                return ResourceManager.GetString("AccountLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название:.
        /// </summary>
        internal static string ActivityNameLbl {
            get {
                return ResourceManager.GetString("ActivityNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить активность.
        /// </summary>
        internal static string AddActivityBtn {
            get {
                return ResourceManager.GetString("AddActivityBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес и индекс.
        /// </summary>
        internal static string AddressLbl {
            get {
                return ResourceManager.GetString("AddressLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите администрирующего.
        /// </summary>
        internal static string AdminPost {
            get {
                return ResourceManager.GetString("AdminPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Классный руководитель:.
        /// </summary>
        internal static string AdminTeacherLbl {
            get {
                return ResourceManager.GetString("AdminTeacherLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуйте, {0}! Выберите следующее действие.
        /// </summary>
        internal static string AuthoredWelkomeLbl {
            get {
                return ResourceManager.GetString("AuthoredWelkomeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № банковской карты.
        /// </summary>
        internal static string BankAccountLbl {
            get {
                return ResourceManager.GetString("BankAccountLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BigBtn {
            get {
                object obj = ResourceManager.GetObject("BigBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения.
        /// </summary>
        internal static string BirthdayLbl {
            get {
                return ResourceManager.GetString("BirthdayLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, проверьте результат экспорта.
        /// </summary>
        internal static string CheckingDataText {
            get {
                return ResourceManager.GetString("CheckingDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка данных.
        /// </summary>
        internal static string CheckingDataTitle {
            get {
                return ResourceManager.GetString("CheckingDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Класс:.
        /// </summary>
        internal static string ClassNameLbl {
            get {
                return ResourceManager.GetString("ClassNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        internal static string CloseBtn {
            get {
                return ResourceManager.GetString("CloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить.
        /// </summary>
        internal static string ContinueBtn {
            get {
                return ResourceManager.GetString("ContinueBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4;5;7;8;10.
        /// </summary>
        internal static string DefaultClasses {
            get {
                return ResourceManager.GetString("DefaultClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский язык;Математика.
        /// </summary>
        internal static string DefaultSubjects {
            get {
                return ResourceManager.GetString("DefaultSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Право;Экономика;Немецкий язык;Французский язык;Экология.
        /// </summary>
        internal static string ExoticSubjects {
            get {
                return ResourceManager.GetString("ExoticSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получить данные.
        /// </summary>
        internal static string ExportBtn {
            get {
                return ResourceManager.GetString("ExportBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получить данные.
        /// </summary>
        internal static string ExportDataBtn {
            get {
                return ResourceManager.GetString("ExportDataBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доп. педагог:.
        /// </summary>
        internal static string ExtraTeacherLbl {
            get {
                return ResourceManager.GetString("ExtraTeacherLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Военкомат.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окончить год.
        /// </summary>
        internal static string FinishYearLbl {
            get {
                return ResourceManager.GetString("FinishYearLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FonPct {
            get {
                object obj = ResourceManager.GetObject("FonPct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ф.И.О..
        /// </summary>
        internal static string FullNameLbl {
            get {
                return ResourceManager.GetString("FullNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните таблицу.
        /// </summary>
        internal static string IncorrectDataTitle {
            get {
                return ResourceManager.GetString("IncorrectDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не все ячейки заполнены.
        /// </summary>
        internal static string IncorrectDataTxtDef {
            get {
                return ResourceManager.GetString("IncorrectDataTxtDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните данные для классов: {0}.
        /// </summary>
        internal static string IncorrectDataTxtExt {
            get {
                return ResourceManager.GetString("IncorrectDataTxtExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подана заявка.
        /// </summary>
        internal static string InitialActivityResult {
            get {
                return ResourceManager.GetString("InitialActivityResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИНН.
        /// </summary>
        internal static string INNLbl {
            get {
                return ResourceManager.GetString("INNLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MiddleBtn {
            get {
                object obj = ResourceManager.GetObject("MiddleBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участник?.
        /// </summary>
        internal static string NeedToProcessLbl {
            get {
                return ResourceManager.GetString("NeedToProcessLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoColofFon {
            get {
                object obj = ResourceManager.GetObject("NoColofFon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не использовать.
        /// </summary>
        internal static string NonUsingLbl {
            get {
                return ResourceManager.GetString("NonUsingLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Литература;Биология;Физика;Химия;Информатика;История;Обществознание;География;Английский язык;Астрономия;Физкультура;ОБЖ;Технология;МХК.
        /// </summary>
        internal static string OlderClassesSubjects {
            get {
                return ResourceManager.GetString("OlderClassesSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВОШ.
        /// </summary>
        internal static string OlympicLbl {
            get {
                return ResourceManager.GetString("OlympicLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Паспорт. данные.
        /// </summary>
        internal static string PassportLbl {
            get {
                return ResourceManager.GetString("PassportLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № телефона.
        /// </summary>
        internal static string PhoneLbl {
            get {
                return ResourceManager.GetString("PhoneLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите класс: .
        /// </summary>
        internal static string PressClassLbl {
            get {
                return ResourceManager.GetString("PressClassLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес проживания.
        /// </summary>
        internal static string PupilsAddressLbl {
            get {
                return ResourceManager.GetString("PupilsAddressLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пол.
        /// </summary>
        internal static string PupilSexLbl {
            get {
                return ResourceManager.GetString("PupilSexLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не может быть прочтён.
        /// </summary>
        internal static string ReadingFileFailureText {
            get {
                return ResourceManager.GetString("ReadingFileFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл успешно прочтён и обрабатывается.
        /// </summary>
        internal static string ReadingFileText {
            get {
                return ResourceManager.GetString("ReadingFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение файла.
        /// </summary>
        internal static string ReadintFileTitle {
            get {
                return ResourceManager.GetString("ReadintFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрировать.
        /// </summary>
        internal static string RegisterBtn {
            get {
                return ResourceManager.GetString("RegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, Зарегистрируйте учреждение!.
        /// </summary>
        internal static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша школа не зарегистрирована.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У Вас имеются повторяющиеся значения.
        /// </summary>
        internal static string RepeatedValues {
            get {
                return ResourceManager.GetString("RepeatedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В файл.
        /// </summary>
        internal static string SaveToFileLbl {
            get {
                return ResourceManager.GetString("SaveToFileLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СНИЛС.
        /// </summary>
        internal static string SNILSLbl {
            get {
                return ResourceManager.GetString("SNILSLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string StatusLbl {
            get {
                return ResourceManager.GetString("StatusLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предметы.
        /// </summary>
        internal static string SubjectLbl {
            get {
                return ResourceManager.GetString("SubjectLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Педагог:.
        /// </summary>
        internal static string TeacherLbl {
            get {
                return ResourceManager.GetString("TeacherLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить активность.
        /// </summary>
        internal static string UpdateActivityBtn {
            get {
                return ResourceManager.GetString("UpdateActivityBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать.
        /// </summary>
        internal static string UsingLbl {
            get {
                return ResourceManager.GetString("UsingLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использование.
        /// </summary>
        internal static string UsingSubjectsLbl {
            get {
                return ResourceManager.GetString("UsingSubjectsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуйтe! Зарегистрируйтесь или авторизируйтесь.
        /// </summary>
        internal static string WelkomeLbl {
            get {
                return ResourceManager.GetString("WelkomeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Достижения.
        /// </summary>
        internal static string YearActivitiesBtn {
            get {
                return ResourceManager.GetString("YearActivitiesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Год рождения.
        /// </summary>
        internal static string YearBirthLbl {
            get {
                return ResourceManager.GetString("YearBirthLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчёт по классу.
        /// </summary>
        internal static string YearlyReportLbl {
            get {
                return ResourceManager.GetString("YearlyReportLbl", resourceCulture);
            }
        }
    }
}
